/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

/**
 *
 * @author abban
 */
public class Caption extends javax.swing.JFrame {

    /**
     * Creates new form Caption
     */
    public Caption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RiddleQuestionLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AnswerTestField = new javax.swing.JTextField();
        RiddelButton = new javax.swing.JButton();
        AnswerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Answer the riddle to get back to the login screen");

        jLabel3.setText("Answer:");

        RiddelButton.setText("Start the riddle");
        RiddelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiddelButtonActionPerformed(evt);
            }
        });

        AnswerButton.setText("Answer");
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AnswerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(AnswerTestField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(RiddleQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RiddelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(RiddleQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AnswerTestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RiddelButton)
                    .addComponent(AnswerButton))
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RiddelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiddelButtonActionPerformed
        // TODO add your handling code here:
        double randome = Math.random()*5+1;
        int random = (int)randome;
        String riddle= "";
        String answerriddle;
        if(random == 1){
            riddle = "What was new, is new again. Rebirth. Restoration. Reformation";
            answerriddle = "Renewal";
        }
        else if(random ==2){
            riddle = "I am first a fraud or a trick. Or perhaps a blend of the two. That’s up to your misinterpretation.";
            answerriddle = "Confusion";
        }
        else if(random == 3){
            riddle = "Fear he who hides behind one.";
            answerriddle = "Mask";
        }
        else if(random == 4){
            riddle = "What is the beginning of eternity, the end of time and space, the beginning of every end and the end of every race?";
            answerriddle = "The letter ‘E’";
        }
        else if(random == 5){
            riddle = "How many sides has a circle?";
            answerriddle = "Two. The inside and the outside.";
        }
        RiddleQuestionLabel.setText(riddle);
        String guess = AnswerTestField.getText();
        RiddelButton.setOpaque(false);
        RiddelButton.setContentAreaFilled(false);
        RiddelButton.setBorderPainted(false);
        RiddelButton.setText(" ");
    }//GEN-LAST:event_RiddelButtonActionPerformed

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        // TODO add your handling code here:
        String riddle = RiddleQuestionLabel.getText();
        String answerriddle = "a";
        if(riddle.equals("What was new, is new again. Rebirth. Restoration. Reformation")){
            answerriddle = "Renewal";
        }
        else if(riddle.equals("I am first a fraud or a trick. Or perhaps a blend of the two. That’s up to your misinterpretation.")){
            answerriddle = "Confusion";
        }
        else if(riddle.equals("Fear he who hides behind one.")){
            answerriddle = "Mask";
        }
        else if(riddle.equals("What is the beginning of eternity, the end of time and space, the beginning of every end and the end of every race?")){
            answerriddle = "The letter ‘E’";
        }
        else if(riddle.equals("How many sides has a circle?")){
            answerriddle = "Two. The inside and the outside.";
        }
        String guess = AnswerTestField.getText();
        if(guess.equals(answerriddle)){
             new LoginScreen().setVisible(true);
             setVisible(false);
        }
        if(!(guess.equals(answerriddle))){
             setVisible(false);
        }
    }//GEN-LAST:event_AnswerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnswerButton;
    private javax.swing.JTextField AnswerTestField;
    private javax.swing.JButton RiddelButton;
    private javax.swing.JLabel RiddleQuestionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
