/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

/**
 *
 * @author abban
 */
public class ShopScreen extends javax.swing.JFrame {

    /**
     * Creates new form ShopScreen
     */
    public ShopScreen() {
        initComponents();
    }
    public ShopScreen(String goldmoney , String res, String damagey,String looty,String kill, String level) {
        initComponents();
        MoneyLabel.setText(goldmoney);
        ResistanceMultiply.setText(res);
        DamageMultiply.setText(damagey);
        LootMultiply.setText(looty);
        LevelLabel.setText(level);
        TotalKillLabel.setText(kill);
        
        double resis = Double.parseDouble(res);
        int price = (int)(125.0*resis);
        ResistanceButton.setText(String.valueOf(price));
        
        double loot = Double.parseDouble(looty);
        int price3 = (int)(500.0*loot);
        LootButton.setText(String.valueOf(price3));
        
        double damage = Double.parseDouble(damagey);
        int price2 = (int)(250*damage);
        DamageButton.setText(String.valueOf(price2));
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ResistanceButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LootButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DamageButton = new javax.swing.JButton();
        ResistanceMultiply = new javax.swing.JLabel();
        LootMultiply = new javax.swing.JLabel();
        DamageMultiply = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MoneyLabel = new javax.swing.JLabel();
        BacktoHomeScreenButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TransactionTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TotalKillLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("This is the shop");

        jLabel2.setText("Increase resistance");

        ResistanceButton.setText("125");
        ResistanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResistanceButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Increase loot multiplier");

        LootButton.setText("500");
        LootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LootButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Increase damage multiplier");

        DamageButton.setText("250");
        DamageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamageButtonActionPerformed(evt);
            }
        });

        ResistanceMultiply.setText("1");

        LootMultiply.setText("1");

        DamageMultiply.setText("1");

        jLabel5.setText("Gold: ");

        MoneyLabel.setText("100");

        BacktoHomeScreenButton.setText("Back to home screen");
        BacktoHomeScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoHomeScreenButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Status:");

        jLabel7.setText("Level:");

        jLabel8.setText("Gold");

        jLabel9.setText("XP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LootButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResistanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DamageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DamageMultiply)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ResistanceMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LootMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(BacktoHomeScreenButton))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TotalKillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(MoneyLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(LevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24))
                                    .addComponent(TransactionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(TransactionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ResistanceButton)
                            .addComponent(ResistanceMultiply))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LootButton)
                            .addComponent(LootMultiply))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DamageButton)
                            .addComponent(DamageMultiply))
                        .addGap(18, 18, 18)
                        .addComponent(BacktoHomeScreenButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(MoneyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(TotalKillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BacktoHomeScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoHomeScreenButtonActionPerformed
        // TODO add your handling code here:
             String cash = MoneyLabel.getText();
             String re = ResistanceMultiply.getText();
             String lootz = LootMultiply.getText();
             String damagez = DamageMultiply.getText();
             String kill = TotalKillLabel.getText();
             String level = LevelLabel.getText();
             new FrontScreen(cash,re,damagez,lootz,kill,level).setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_BacktoHomeScreenButtonActionPerformed

    private void ResistanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResistanceButtonActionPerformed
        // TODO add your handling code here:
        int gold = Integer.parseInt(MoneyLabel.getText());
        double resistance = Double.parseDouble(ResistanceMultiply.getText());
        double price = Double.parseDouble(ResistanceButton.getText());
        ResistanceButton.setText(String.valueOf(price));
        if(gold >= price){
            gold = (int)(gold - price);
            resistance = resistance + 0.1;
            resistance*= 10;
            resistance = Math.round(resistance);
            resistance/= 10;
            TransactionTextField.setText("TRANSACTION SUCCESSFUL"); 
            price = 125.0 * resistance;
            price = (int)price;
            ResistanceButton.setText(String.valueOf(price));
        }
        else if(gold < price){
            TransactionTextField.setText("TRANSACTION FAILED");
        }
        String money = String.valueOf(gold);
        String r = String.valueOf(resistance);
        MoneyLabel.setText(money);
        ResistanceMultiply.setText(r);
    }//GEN-LAST:event_ResistanceButtonActionPerformed

    private void DamageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamageButtonActionPerformed
        // TODO add your handling code here:
        int gold = Integer.parseInt(MoneyLabel.getText());
        double damage = Double.parseDouble(DamageMultiply.getText());
        double price = Double.parseDouble(DamageButton.getText());
        DamageButton.setText(String.valueOf(price));
        if(gold >= price){
            gold = gold - 250;
            damage = damage + 0.1;
            damage*= 10;
            damage = Math.round(damage);
            damage/= 10;
            TransactionTextField.setText("TRANSACTION SUCCESSFUL"); 
           price = 250.0 * damage;
            price = (int)price;
            DamageButton.setText(String.valueOf(price));
        }
        else if(gold < price){
            TransactionTextField.setText("TRANSACTION FAILED");
        }
        String money = String.valueOf(gold);
        String de = String.valueOf(damage);
        MoneyLabel.setText(money);
        DamageMultiply.setText(de);
    }//GEN-LAST:event_DamageButtonActionPerformed

    private void LootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LootButtonActionPerformed
        // TODO add your handling code here:
        int gold = Integer.parseInt(MoneyLabel.getText());
        double loot = Double.parseDouble(LootMultiply.getText());
        double price = Double.parseDouble(LootButton.getText());
        LootButton.setText(String.valueOf(price));
        
        if(gold >= price){
            gold = gold - 500;
            loot = loot + 0.1;
            loot*= 10;
            loot = Math.round(loot);
            loot/= 10;
            TransactionTextField.setText("TRANSACTION SUCCESSFUL");
            price = 500.0 * loot;
            price = (int)price;
            LootButton.setText(String.valueOf(price));
        }
        else if(gold < price){
            TransactionTextField.setText("TRANSACTION FAILED");
        }
        String money = String.valueOf(gold);
        String lo = String.valueOf(loot);
        MoneyLabel.setText(money);
        LootMultiply.setText(lo);
    }//GEN-LAST:event_LootButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoHomeScreenButton;
    private javax.swing.JButton DamageButton;
    private javax.swing.JLabel DamageMultiply;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JButton LootButton;
    private javax.swing.JLabel LootMultiply;
    private javax.swing.JLabel MoneyLabel;
    private javax.swing.JButton ResistanceButton;
    private javax.swing.JLabel ResistanceMultiply;
    private javax.swing.JLabel TotalKillLabel;
    private javax.swing.JTextField TransactionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
