/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Safety;

/**
 *
 * @author abban
 */
public class Letters extends javax.swing.JFrame {

    /**
     * Creates new form Letters
     */
    public Letters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LetterAButton = new javax.swing.JButton();
        LetterBButton = new javax.swing.JButton();
        LetterCButton = new javax.swing.JButton();
        LetterDButton = new javax.swing.JButton();
        LetterEButton = new javax.swing.JButton();
        LetterFButton = new javax.swing.JButton();
        LetterGButton = new javax.swing.JButton();
        LetterHButton = new javax.swing.JButton();
        LetterIButton = new javax.swing.JButton();
        LetterJButton = new javax.swing.JButton();
        LetterKButton = new javax.swing.JButton();
        LetterLButton = new javax.swing.JButton();
        LetterMButton = new javax.swing.JButton();
        LetterNButton = new javax.swing.JButton();
        LetterOButton = new javax.swing.JButton();
        LetterPButton = new javax.swing.JButton();
        LetterQButton = new javax.swing.JButton();
        LetterRButton = new javax.swing.JButton();
        LetterSButton = new javax.swing.JButton();
        LetterTButton = new javax.swing.JButton();
        LetterVButton = new javax.swing.JButton();
        LetterUButton = new javax.swing.JButton();
        LetterWButton = new javax.swing.JButton();
        LetterXButton = new javax.swing.JButton();
        LetterYButton = new javax.swing.JButton();
        LetterZButton = new javax.swing.JButton();
        ShiftButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScreenTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LetterAButton.setText("a");
        LetterAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterAButtonActionPerformed(evt);
            }
        });

        LetterBButton.setText("b");
        LetterBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterBButtonActionPerformed(evt);
            }
        });

        LetterCButton.setText("c");
        LetterCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterCButtonActionPerformed(evt);
            }
        });

        LetterDButton.setText("d");
        LetterDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterDButtonActionPerformed(evt);
            }
        });

        LetterEButton.setText("e");
        LetterEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterEButtonActionPerformed(evt);
            }
        });

        LetterFButton.setText("f");
        LetterFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterFButtonActionPerformed(evt);
            }
        });

        LetterGButton.setText("g");
        LetterGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterGButtonActionPerformed(evt);
            }
        });

        LetterHButton.setText("h");
        LetterHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterHButtonActionPerformed(evt);
            }
        });

        LetterIButton.setText("i");
        LetterIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterIButtonActionPerformed(evt);
            }
        });

        LetterJButton.setText("j");
        LetterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterJButtonActionPerformed(evt);
            }
        });

        LetterKButton.setText("k");
        LetterKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterKButtonActionPerformed(evt);
            }
        });

        LetterLButton.setText("l");
        LetterLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterLButtonActionPerformed(evt);
            }
        });

        LetterMButton.setText("m");
        LetterMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterMButtonActionPerformed(evt);
            }
        });

        LetterNButton.setText("n");
        LetterNButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterNButtonActionPerformed(evt);
            }
        });

        LetterOButton.setText("o");
        LetterOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterOButtonActionPerformed(evt);
            }
        });

        LetterPButton.setText("p");
        LetterPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterPButtonActionPerformed(evt);
            }
        });

        LetterQButton.setText("q");
        LetterQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterQButtonActionPerformed(evt);
            }
        });

        LetterRButton.setText("r");
        LetterRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterRButtonActionPerformed(evt);
            }
        });

        LetterSButton.setText("s");
        LetterSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterSButtonActionPerformed(evt);
            }
        });

        LetterTButton.setText("t");
        LetterTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterTButtonActionPerformed(evt);
            }
        });

        LetterVButton.setText("v");
        LetterVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterVButtonActionPerformed(evt);
            }
        });

        LetterUButton.setText("u");
        LetterUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterUButtonActionPerformed(evt);
            }
        });

        LetterWButton.setText("w");
        LetterWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterWButtonActionPerformed(evt);
            }
        });

        LetterXButton.setText("x");
        LetterXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterXButtonActionPerformed(evt);
            }
        });

        LetterYButton.setText("y");
        LetterYButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterYButtonActionPerformed(evt);
            }
        });

        LetterZButton.setText("z");
        LetterZButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterZButtonActionPerformed(evt);
            }
        });

        ShiftButton.setText("Shift");
        ShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiftButtonActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");

        ScreenTextArea.setColumns(20);
        ScreenTextArea.setRows(5);
        jScrollPane1.setViewportView(ScreenTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LetterYButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterZButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShiftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LetterSButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterTButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterVButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterUButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterWButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterXButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LetterMButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterNButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterOButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterPButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterQButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterRButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LetterGButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LetterAButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LetterBButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterCButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterDButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterEButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterFButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LetterHButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterIButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterJButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(LetterKButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LetterLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterAButton)
                    .addComponent(LetterBButton)
                    .addComponent(LetterCButton)
                    .addComponent(LetterDButton)
                    .addComponent(LetterEButton)
                    .addComponent(LetterFButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterGButton)
                    .addComponent(LetterHButton)
                    .addComponent(LetterIButton)
                    .addComponent(LetterJButton)
                    .addComponent(LetterKButton)
                    .addComponent(LetterLButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterMButton)
                    .addComponent(LetterNButton)
                    .addComponent(LetterOButton)
                    .addComponent(LetterPButton)
                    .addComponent(LetterQButton)
                    .addComponent(LetterRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterSButton)
                    .addComponent(LetterTButton)
                    .addComponent(LetterVButton)
                    .addComponent(LetterUButton)
                    .addComponent(LetterWButton)
                    .addComponent(LetterXButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterYButton)
                    .addComponent(LetterZButton)
                    .addComponent(ShiftButton)
                    .addComponent(SubmitButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LetterAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterAButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterAButtonActionPerformed

    private void LetterEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterEButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterEButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterEButtonActionPerformed

    private void LetterLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterLButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterLButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterLButtonActionPerformed

    private void LetterMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterMButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterMButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterMButtonActionPerformed

    private void LetterNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterNButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterNButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterNButtonActionPerformed

    private void LetterOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterOButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterOButtonActionPerformed

    private void LetterPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterPButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterPButtonActionPerformed

    private void LetterQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterQButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterQButtonActionPerformed

    private void LetterRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterRButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterRButtonActionPerformed

    private void LetterSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterSButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterSButtonActionPerformed

    private void LetterTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterTButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterTButtonActionPerformed

    private void LetterVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterVButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterVButtonActionPerformed

    private void LetterUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterUButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterUButtonActionPerformed

    private void LetterWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterWButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterWButtonActionPerformed

    private void LetterXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterXButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterXButtonActionPerformed

    private void LetterYButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterYButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterYButtonActionPerformed

    private void LetterZButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterZButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterZButtonActionPerformed

    private void LetterKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterKButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterKButtonActionPerformed

    private void ShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        if(letter.equals("a")){
            LetterAButton.setText("A");
        }
        else{
            LetterAButton.setText("a");
        }
        
    }//GEN-LAST:event_ShiftButtonActionPerformed

    private void LetterBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterBButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterBButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterBButtonActionPerformed

    private void LetterCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterCButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterCButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterCButtonActionPerformed

    private void LetterDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterDButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterDButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterDButtonActionPerformed

    private void LetterFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterFButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterFButtonActionPerformed

    private void LetterGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterGButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterGButtonActionPerformed

    private void LetterHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterHButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterHButtonActionPerformed

    private void LetterIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterIButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterIButtonActionPerformed

    private void LetterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterJButtonActionPerformed
        // TODO add your handling code here:
        String letter = LetterAButton.getText();
        String screen = ScreenTextArea.getText() + letter;
        ScreenTextArea.setText(screen);
    }//GEN-LAST:event_LetterJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Letters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Letters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Letters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Letters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Letters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LetterAButton;
    private javax.swing.JButton LetterBButton;
    private javax.swing.JButton LetterCButton;
    private javax.swing.JButton LetterDButton;
    private javax.swing.JButton LetterEButton;
    private javax.swing.JButton LetterFButton;
    private javax.swing.JButton LetterGButton;
    private javax.swing.JButton LetterHButton;
    private javax.swing.JButton LetterIButton;
    private javax.swing.JButton LetterJButton;
    private javax.swing.JButton LetterKButton;
    private javax.swing.JButton LetterLButton;
    private javax.swing.JButton LetterMButton;
    private javax.swing.JButton LetterNButton;
    private javax.swing.JButton LetterOButton;
    private javax.swing.JButton LetterPButton;
    private javax.swing.JButton LetterQButton;
    private javax.swing.JButton LetterRButton;
    private javax.swing.JButton LetterSButton;
    private javax.swing.JButton LetterTButton;
    private javax.swing.JButton LetterUButton;
    private javax.swing.JButton LetterVButton;
    private javax.swing.JButton LetterWButton;
    private javax.swing.JButton LetterXButton;
    private javax.swing.JButton LetterYButton;
    private javax.swing.JButton LetterZButton;
    private javax.swing.JTextArea ScreenTextArea;
    private javax.swing.JButton ShiftButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
