/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author abban
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Number1 = new javax.swing.JLabel();
        Number1Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Number2Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AnsButton = new javax.swing.JButton();
        ConstantLable2 = new javax.swing.JLabel();
        Button0 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        PlusButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JToggleButton();
        AnswerButton = new javax.swing.JToggleButton();
        DivideButton = new javax.swing.JToggleButton();
        MultiplyButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnswerTextArea = new javax.swing.JTextArea();
        ButtonPI = new javax.swing.JButton();
        SquareRootButton = new javax.swing.JButton();
        SquareButton = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        Num1Label = new javax.swing.JLabel();
        Num2Label = new javax.swing.JLabel();
        EquationLabel = new javax.swing.JLabel();
        HelpButton = new javax.swing.JButton();
        SymbolLabel = new javax.swing.JLabel();
        PreviousNumberLabel = new javax.swing.JLabel();
        NumberofTimesLabel = new javax.swing.JLabel();
        BringTheOldDataButton = new javax.swing.JButton();
        QuadraticEquationButton = new javax.swing.JButton();
        xsqaureLabel = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        constantLabel = new javax.swing.JLabel();

        jLabel1.setText("Only 2 numbers are allowed:");

        Number1.setText("Number 1: ");

        Number1Label.setText("N/A");

        jLabel2.setText("Number 2:");

        Number2Label.setText("N/A");

        jLabel5.setText("jLabel5");

        jLabel4.setText("jLabel4");

        AnsButton.setText("Ans");

        ConstantLable2.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        PlusButton.setText("+");
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        MinusButton.setText("-");
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        AnswerButton.setText("=");
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });

        DivideButton.setText("÷");
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideButtonActionPerformed(evt);
            }
        });

        MultiplyButton.setText("x");
        MultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyButtonActionPerformed(evt);
            }
        });

        AnswerTextArea.setColumns(20);
        AnswerTextArea.setRows(5);
        AnswerTextArea.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                AnswerTextAreaInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(AnswerTextArea);

        ButtonPI.setText("π");
        ButtonPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPIActionPerformed(evt);
            }
        });

        SquareRootButton.setText("√");
        SquareRootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareRootButtonActionPerformed(evt);
            }
        });

        SquareButton.setText("x²");
        SquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareButtonActionPerformed(evt);
            }
        });

        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        HelpButton.setText("Help");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        BringTheOldDataButton.setText("Ans");
        BringTheOldDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BringTheOldDataButtonActionPerformed(evt);
            }
        });

        QuadraticEquationButton.setText("Quadratic equation");
        QuadraticEquationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuadraticEquationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(90, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonPI)
                                .addGap(18, 18, 18)
                                .addComponent(SquareRootButton)
                                .addGap(18, 18, 18)
                                .addComponent(SquareButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xsqaureLabel)
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ClearButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Button4)
                                                        .addComponent(Button1))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Button7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Button8)))
                                            .addGap(21, 21, 21)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Button6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(QuadraticEquationButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Button0)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(SymbolLabel)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Num1Label)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Num2Label))
                                                            .addComponent(EquationLabel)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(55, 55, 55)
                                                                .addComponent(NumberofTimesLabel)))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(PreviousNumberLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(constantLabel)
                                                                .addGap(56, 56, 56)))
                                                        .addComponent(xLabel)
                                                        .addGap(103, 103, 103))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BringTheOldDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(AnswerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DivideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(MultiplyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PlusButton)
                                            .addComponent(MinusButton)))
                                    .addComponent(HelpButton, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1)
                    .addComponent(Button2)
                    .addComponent(PlusButton)
                    .addComponent(DivideButton)
                    .addComponent(Button3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button5)
                    .addComponent(Button6)
                    .addComponent(MinusButton)
                    .addComponent(MultiplyButton)
                    .addComponent(Button4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnswerButton)
                    .addComponent(Button7)
                    .addComponent(Button8)
                    .addComponent(Button9)
                    .addComponent(Button0))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Num1Label)
                            .addComponent(Num2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EquationLabel)
                        .addGap(36, 36, 36)
                        .addComponent(SymbolLabel)
                        .addGap(40, 40, 40)
                        .addComponent(constantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PreviousNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HelpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BringTheOldDataButton)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonPI)
                            .addComponent(SquareRootButton)
                            .addComponent(SquareButton)
                            .addComponent(NumberofTimesLabel)
                            .addComponent(xsqaureLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuadraticEquationButton)
                            .addComponent(xLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyButtonActionPerformed
        String screen = AnswerTextArea.getText();
        String num1 = Num1Label.getText();

        AnswerTextArea.setText(screen + "*");


        if (num1.equals("")) {
            Num1Label.setText(screen);
            Num1Label.setVisible(false);
        }
    }//GEN-LAST:event_MultiplyButtonActionPerformed

    private void ButtonPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPIActionPerformed
        // TODO add your handling code here:
        double num = Integer.parseInt(AnswerTextArea.getText());
        num *= Math.PI;
        num *= 100;
        num = Math.round(num);
        num /= 100;
        AnswerTextArea.setText(String.valueOf(num));
    }//GEN-LAST:event_ButtonPIActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void AnswerTextAreaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_AnswerTextAreaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerTextAreaInputMethodTextChanged

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideButtonActionPerformed
        String screen = AnswerTextArea.getText();
        String num1 = Num1Label.getText();

        AnswerTextArea.setText(screen + "/");

        if (num1.equals("")) {
            Num1Label.setText(screen);
            Num1Label.setVisible(false);
        }
    }//GEN-LAST:event_DivideButtonActionPerformed

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed
        String screen = AnswerTextArea.getText();
        String num1 = Num1Label.getText();

        AnswerTextArea.setText(screen + "+");

        if (num1.equals("")) {
            Num1Label.setText(screen);
            Num1Label.setVisible(false);
        }
    }//GEN-LAST:event_PlusButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        String screen = AnswerTextArea.getText();
        String num1 = Num1Label.getText();

        AnswerTextArea.setText(screen + "-");

        if (num1.equals("")) {
            Num1Label.setText(screen);
            Num1Label.setVisible(false);
        }
    }//GEN-LAST:event_MinusButtonActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        AnswerTextArea.setText(screen + "4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        String screen = AnswerTextArea.getText();
        char divide = '/';
        char plus = '+';
        char multiply = '*';
        char minus = '-';

        String num1 = Num1Label.getText();
        String num2 = Num2Label.getText();
        
        if(num2.equals("")){
            int location = num1.length();
            screen = screen.substring(location + 1, screen.length());
            Num2Label.setText(screen);
            Num2Label.setVisible(false);
        }
        for (int i = 0; i < screen.length(); i++) {
            char find = screen.charAt(i);
            if(find == divide) {
                double word1 = Double.parseDouble(Num1Label.getText());
                double word2 = Double.parseDouble(Num2Label.getText());
                double sum = word1 / word2;
                AnswerTextArea.setText(String.valueOf(sum));
                Num1Label.setText(String.valueOf(sum));
                Num1Label.setVisible(false);
                SymbolLabel.setText(String.valueOf(divide));
                SymbolLabel.setVisible(false);
                PreviousNumberLabel.setText(String.valueOf(word2));
                PreviousNumberLabel.setVisible(false);
                Num2Label.setText("");
            } 
            else if (find == plus) {
                int word1 = Integer.parseInt(Num1Label.getText());
                int word2 = Integer.parseInt(Num2Label.getText());
                int sum = word1 + word2;
                AnswerTextArea.setText(String.valueOf(sum));
                Num1Label.setText(String.valueOf(sum));
                Num1Label.setVisible(false);
                SymbolLabel.setText(String.valueOf(plus));
                SymbolLabel.setVisible(false);
                PreviousNumberLabel.setText(String.valueOf(word2));
                PreviousNumberLabel.setVisible(false);
                Num2Label.setText("");

            } else if (find == multiply) {
                double word1 = Double.parseDouble(Num1Label.getText());
                double word2 = Double.parseDouble(Num2Label.getText());
                double sum = word1 * word2;
                AnswerTextArea.setText(String.valueOf(sum));
                Num1Label.setText(String.valueOf(sum));
                Num1Label.setVisible(false);
                SymbolLabel.setText(String.valueOf(multiply));
                SymbolLabel.setVisible(false);
                PreviousNumberLabel.setText(String.valueOf(word2));
                PreviousNumberLabel.setVisible(false);
                Num2Label.setText("");
            } else if (find == minus) {
                int word1 = Integer.parseInt(Num1Label.getText());
                int word2 = Integer.parseInt(Num2Label.getText());
                int sum = word1 - word2;
                AnswerTextArea.setText(String.valueOf(sum));
                Num1Label.setText(String.valueOf(sum));
                Num1Label.setVisible(false);
                SymbolLabel.setText(String.valueOf(minus));
                SymbolLabel.setVisible(false);
                PreviousNumberLabel.setText(String.valueOf(word2));
                PreviousNumberLabel.setVisible(false);
                Num2Label.setText("");
            }
        }
    }//GEN-LAST:event_AnswerButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        AnswerTextArea.setText("");
        Num1Label.setText("");
        Num2Label.setText("");
        PreviousNumberLabel.setText("");
        SymbolLabel.setText("");
        xsqaureLabel.setText("");
        xLabel.setText("");
        constantLabel.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void SquareRootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareRootButtonActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(AnswerTextArea.getText());
        num = Math.sqrt(num);
        AnswerTextArea.setText(String.valueOf(num));
    }//GEN-LAST:event_SquareRootButtonActionPerformed

    private void SquareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareButtonActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(AnswerTextArea.getText());
        num = Math.pow(num, 2);
        AnswerTextArea.setText(String.valueOf(num));
    }//GEN-LAST:event_SquareButtonActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
      new Help().setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void BringTheOldDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BringTheOldDataButtonActionPerformed
        // TODO add your handling code here:
        String PreviousNumber = PreviousNumberLabel.getText();
        String screen = AnswerTextArea.getText();
        
        if(!(PreviousNumber.equals(""))){
            String symbol = SymbolLabel.getText();
            if(symbol.equals("/")){
                screen = screen + "/" + PreviousNumber;
                AnswerTextArea.setText(screen);
            }
            else if(symbol.equals("*")){
                screen = screen + "*" + PreviousNumber;
                AnswerTextArea.setText(screen);
            }
            else if(symbol.equals("-")){
                screen = screen + "-" + PreviousNumber;
                AnswerTextArea.setText(screen);
            }
            else if(symbol.equals("+")){
                screen = screen + "+" + PreviousNumber;
                AnswerTextArea.setText(screen);
            }
        }
    }//GEN-LAST:event_BringTheOldDataButtonActionPerformed

    private void QuadraticEquationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuadraticEquationButtonActionPerformed
        // TODO add your handling code here:
        String screen = AnswerTextArea.getText();
        String aStr = xsqaureLabel.getText();
        String bStr = xLabel.getText();
        String cStr= constantLabel.getText();
        double a = 0;
        double b = 0;
        double c = 0;
        
        if(aStr.equals("")){
            a = Double.parseDouble(screen);
            xsqaureLabel.setText(String.valueOf(a));
            AnswerTextArea.setText("");
        }
        else if(bStr.equals("")){
            b = Double.parseDouble(screen);
            xLabel.setText(String.valueOf(b));
            AnswerTextArea.setText("");
        }
        else if(cStr.equals("")){
            c = Double.parseDouble(screen);
            constantLabel.setText(String.valueOf(c));
            AnswerTextArea.setText("");
        }
        else if(!(cStr.equals("") && bStr.equals("") && aStr.equals(""))){
            a = Double.parseDouble(xsqaureLabel.getText());
            b = Double.parseDouble(xLabel.getText());
            c = Double.parseDouble(constantLabel.getText());
            double sum1part1 = -1*b;
            double sum1part2 = Math.pow(b, 2);
            double sum1part3 = 4*c*a;
            double sum1part4 = 2*a;
            double answer1 = (sum1part1 - Math.sqrt(sum1part2 - sum1part3))/sum1part4;
            double answer2 = (sum1part1 + Math.sqrt(sum1part2 - sum1part3))/sum1part4;
            AnswerTextArea.setText("The answers are: " + answer1 + " or " + answer2 );
        }
    }//GEN-LAST:event_QuadraticEquationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnsButton;
    private javax.swing.JToggleButton AnswerButton;
    private javax.swing.JTextArea AnswerTextArea;
    private javax.swing.JButton BringTheOldDataButton;
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonPI;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel ConstantLable2;
    private javax.swing.JToggleButton DivideButton;
    private javax.swing.JLabel EquationLabel;
    private javax.swing.JButton HelpButton;
    private javax.swing.JToggleButton MinusButton;
    private javax.swing.JToggleButton MultiplyButton;
    private javax.swing.JLabel Num1Label;
    private javax.swing.JLabel Num2Label;
    private javax.swing.JLabel Number1;
    private javax.swing.JLabel Number1Label;
    private javax.swing.JLabel Number2Label;
    private javax.swing.JLabel NumberofTimesLabel;
    private javax.swing.JButton PlusButton;
    private javax.swing.JLabel PreviousNumberLabel;
    private javax.swing.JButton QuadraticEquationButton;
    private javax.swing.JButton SquareButton;
    private javax.swing.JButton SquareRootButton;
    private javax.swing.JLabel SymbolLabel;
    private javax.swing.JLabel constantLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xsqaureLabel;
    // End of variables declaration//GEN-END:variables
}
